apiVersion: v1
kind: Service
metadata:
  name: airflow-flower-service
spec:
  selector:
    app: airflow-flower
  ports:
    - port: 5555
      nodePort: 31321
      protocol: TCP
      targetPort: 5555
  type: LoadBalancer
