apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-service
spec:
  selector:
    app: airflow-webserver
  ports:
    - port: 8080
      nodePort: 31322
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
