kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry-data-pv-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-cephfs
