kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry-certs-pv-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
