kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-logs-pv-claim    
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
