kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: airflow-data-pv-claim
spec: 
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
