kind: PersistentVolume 
apiVersion: v1 
metadata: 
  name: airflow-mysql-pv-volume 
  labels: 
    type: local 
    app: airflow-mysql
spec: 
  storageClassName: manual 
  capacity: 
    storage: 5Gi 
  accessModes: 
    - ReadWriteMany 
  hostPath: 
    path: "/opt/data" 
--- 
kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: airflow-mysql-pv-claim 
  labels: 
    app: airflow-mysql 
spec: 
  storageClassName: manual 
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 5Gi 
