apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mysql 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: mysql 
  template: 
    metadata: 
      labels: 
        app: mysql 
    spec: 
      containers: 
        - name: mysql 
          image: mysql:8.0
          imagePullPolicy: "IfNotPresent" 
          ports: 
            - containerPort: 5432 
          envFrom: 
            - configMapRef: 
                name: mysql-config
          volumeMounts: 
            - mountPath: /var/lib/postgresql/data 
              name: mysqldb
          livenessProbe:
            exec:
              command:
                - /usr/bin/mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes: 
        - name: mysqldb 
          persistentVolumeClaim: 
            claimName: mysql-pv-claim
