apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: airflow-mysql 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: airflow-mysql 
  template: 
    metadata: 
      labels: 
        app: airflow-mysql 
    spec: 
      containers: 
        - name: airflow-mysql 
          image: mysql:8.0
          imagePullPolicy: "IfNotPresent" 
          resources:
            requests:
              memory: "2048Mi"
              cpu: "500m"
          ports: 
            - containerPort: 5432 
          envFrom: 
            - configMapRef: 
                name: airflow-mysql-config
          volumeMounts: 
            - mountPath: /var/lib/mysql
              name: airflowmysqldb
      volumes: 
        - name: airflowmysqldb 
          persistentVolumeClaim: 
            claimName: airflow-mysql-pv-claim
