apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: airflow-init
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: airflow-init
  template: 
    metadata: 
      labels: 
        app: airflow-init
    spec: 
      containers: 
        - name: airflow-init
          image: alpine:3.14
          imagePullPolicy: "IfNotPresent" 
          resources:
            requests:
              memory: "128Mi"
          command: 
            - /bin/sh
          args:
            - -c
            - "while true; do sleep 1000; done"
          volumeMounts: 
            - mountPath: /xx/dags
              name: airflowdags
            - mountPath: /xx/logs
              name: airflowlogs
            - mountPath: /xx/plugins
              name: airflowplugins
            - mountPath: /xx/data
              name: airflowdata
      volumes: 
        - name: airflowdags
          persistentVolumeClaim: 
            claimName: airflow-dags-pv-claim
        - name: airflowlogs
          persistentVolumeClaim:
            claimName: airflow-logs-pv-claim
        - name: airflowplugins
          persistentVolumeClaim:
            claimName: airflow-plugins-pv-claim
        - name: airflowdata
          persistentVolumeClaim:
            claimName: airflow-data-pv-claim
