- hosts: a2
  become: True
  tasks:
  - name: Ensure required packages are installed
    dnf:
      name:
        - python39
        - python39-devel
        - python39-pip
        - gcc
      state: latest
