apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc
spec:
  replicas: 2 # number of the pod
  selector: # The pod selector determining what pods the RC is operating on
    app: http-rc-app # label value
  template: # pod template
    metadata:
      labels:
        app: http-rc-app # label value
    spec:
      containers:
      - image: httpd # image used to run container
        name: http-rc-app # name of the container
        ports:
          - containerPort: 80 # pod of the container
