apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: uweb-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uweb
  template:
    metadata:
      labels:
        app: uweb
    spec:
      containers:
      - image: cuhuuhoang/uweb
        name: uweb
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: uweb
spec:
  selector:
    app: uweb # label selectors Pod redis
  ports:
    - port: 80 # port of the serivce
      targetPort: 8080 # port of the container that service will forward to
