apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: uweb-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uweb
  template:
    metadata:
      labels:
        app: uweb
    spec:
      containers:
      - image: cuhuuhoang/uweb
        name: uweb
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: uweb
spec:
  selector:
    app: uweb
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
