kind: PersistentVolume 
apiVersion: v1 
metadata: 
  name: airflow-dags-pv-volume 
  labels: 
    type: local 
    app: airflow
spec: 
  storageClassName: manual 
  capacity: 
    storage: 5Gi 
  accessModes: 
    - ReadWriteMany 
  hostPath: 
    path: "/var/data/airflow/dags"
--- 
kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: airflow-dags-pv-claim
spec: 
  storageClassName: manual 
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: 5Gi
