apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: airflow-core-config 
data: 
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://user_airflow:pwairflow@airflow-mysql/airflow
  AIRFLOW__CELERY__RESULT_BACKEND: db+mysql://user_airflow:pwairflow@airflow-mysql/airflow
  AIRFLOW__CELERY__BROKER_URL: redis://:@airflow-redis:6379/0
  AIRFLOW__CORE__FERNET_KEY: ''
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
  AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
