kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: airflow-dags-pv-claim
spec: 
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-cephfs
