apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: airflow-redis
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: airflow-redis
  template: 
    metadata: 
      labels: 
        app: airflow-redis
    spec: 
      containers: 
        - name: airflow-redis
          image: redis:latest
          imagePullPolicy: "IfNotPresent" 
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          ports: 
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: airflowredisdata
      volumes: 
        - name: airflowredisdata
          persistentVolumeClaim: 
            claimName: airflow-redis-pv-claim
