apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: airflow-scheduler
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: airflow-scheduler
  template: 
    metadata: 
      labels: 
        app: airflow-scheduler
    spec: 
      containers: 
        - name: airflow-scheduler
          image: a1.vt:31320/airflow:1.0.0
          imagePullPolicy: "Always" 
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"
          command: 
            - /entrypoint
          args: 
            - scheduler 
          ports: 
            - containerPort: 8080
          envFrom: 
            - configMapRef: 
                name: airflow-core-config
          volumeMounts: 
            - mountPath: /opt/airflow/dags/pull
              name: airflowdags
            - mountPath: /opt/airflow/logs
              name: airflowlogs
            - mountPath: /opt/airflow/plugins
              name: airflowplugins
      securityContext:
        runAsUser: 50000
      volumes: 
        - name: airflowdags
          persistentVolumeClaim: 
            claimName: airflow-dags-pv-claim
        - name: airflowlogs
          persistentVolumeClaim:
            claimName: airflow-logs-pv-claim
        - name: airflowplugins
          persistentVolumeClaim:
            claimName: airflow-plugins-pv-claim
