apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: airflow-worker1
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: airflow-worker1
  template: 
    metadata: 
      labels: 
        app: airflow-worker1
    spec: 
      containers: 
        - name: airflow-worker1
          image: apache/airflow:2.4.2
          imagePullPolicy: "IfNotPresent" 
          resources:
            requests:
              memory: "2048Mi"
          command: 
            - airflow 
          args: 
            - celery
            - worker
          ports: 
            - containerPort: 8080
          envFrom: 
            - configMapRef: 
                name: airflow-core-config
          env:
            - name: DUMB_INIT_SETSID
              value: "0"
          volumeMounts: 
            - mountPath: /opt/airflow/dags
              name: airflowdags
            - mountPath: /opt/airflow/logs
              name: airflowlogs
            - mountPath: /opt/airflow/plugins
              name: airflowplugins
      securityContext:
        runAsUser: 50000
        fsGroup: 50000
      volumes: 
        - name: airflowdags
          persistentVolumeClaim: 
            claimName: airflow-dags-pv-claim
        - name: airflowlogs
          persistentVolumeClaim:
            claimName: airflow-logs-pv-claim
        - name: airflowplugins
          persistentVolumeClaim:
            claimName: airflow-plugins-pv-claim
